-- Run after supabase-setup.sql. Existing rows stay UNVERIFIED because old dates
-- were generated by the importer. Re-import only genuinely dated source data.
begin;
alter table public.daily_data add column if not exists source_verified boolean not null default false;
alter table public.daily_data add column if not exists source_url text;
alter table public.daily_data add column if not exists fundamentals_date date;

-- Abort safely if duplicates exist; resolve them against the source first.
-- This index is necessary for idempotent stock/date upserts.
create unique index if not exists daily_data_stock_date_unique on public.daily_data(stock_id, date);


create table if not exists public.waitlist (
  id bigint generated always as identity primary key,
  email text not null unique check (email = lower(trim(email)) and length(email) <= 254),
  source text not null default 'website',
  created_at timestamptz not null default now()
);
alter table public.waitlist enable row level security;
revoke all on public.waitlist from anon, authenticated;
grant all on public.waitlist to service_role;
grant usage, select on sequence public.waitlist_id_seq to service_role;

create table if not exists public.research_explanations (
  signature text primary key,
  stock_id integer not null references public.stocks(id) on delete cascade,
  explanation_bn text not null,
  created_at timestamptz not null default now()
);
alter table public.research_explanations enable row level security;
revoke all on public.research_explanations from anon, authenticated;
grant all on public.research_explanations to service_role;

-- Direct public reads of legacy cached scores could reveal misleading old data.
-- All browser traffic now uses the same-origin server API.
revoke all on public.stocks, public.daily_data, public.factor_scores from anon, authenticated;
grant all on public.stocks, public.daily_data, public.factor_scores to service_role;
commit;
